import React from "react";
import type { Metadata } from "next";

import s from "./styles.module.css";

type AboutLayout = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  title: "About page",
  description: "Generated by create next app",
};

const AboutLayout: React.FC<AboutLayout> = ({ children }) => {
  return (
    <>
      <nav>About Navbar</nav>
      <main className={s.main}>{children}</main>
    </>
  );
};

export default AboutLayout;
