import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <h1>My navbar</h1>
        </nav>
        {children}
      </body>
    </html>
  );
}
